AWSTemplateFormatVersion: '2010-09-09'
Description: Outputs the JPEG bits to a FIFO file on AWS DeepLens
Resources:
  Bucket1:
    Type: AWS::S3::Bucket
  deeplensfacedetection:
    Properties:
      CodeUri: s3://deeplens-face-detection/bba29ac6b82d675e6fd5b0cb251a241d
      Description: Outputs the JPEG bits to a FIFO file on AWS DeepLens
      Handler: greengrass_face_detection.function_handler
      MemorySize: 1536
      Role: arn:aws:iam::<your_aws_account_number>:role/AWSDeepLensLambdaRole
      Runtime: python2.7
      Timeout: 3
    Type: AWS::Serverless::Function
  rekognizeEmotions:
    Properties:
      CodeUri: s3://deeplens-face-detection/bba29ac6b82d675e6fd5b0cb251a241d
      Description: An Amazon S3 trigger that uses rekognition APIs to detect faces
      Events:
        BucketEvent1:
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
            - s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: faces/
                - Name: suffix
                  Value: jpg
          Type: S3
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::<your_aws_account_number>:role/service-role/rekognize-faces-role
      Runtime: python2.7
      Tags:
        lambda-console:blueprint: rekognition-python
      Timeout: 3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
