AWSTemplateFormatVersion: '2010-09-09'
Description: Outputs the JPEG bits to a FIFO file on AWS DeepLens
Resources:
  DeeplensHackBucket:
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName:
        Fn::Join:
        - ''
        - - deeplens-hack-
          - Ref: AWS::AccountId
    Type: AWS::S3::Bucket
  RekognizeFacesDDB:
    Properties:
      AttributeDefinitions:
      - AttributeName: s3key
        AttributeType: S
      KeySchema:
      - AttributeName: s3key
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName: recognize-faces
    Type: AWS::DynamoDB::Table
  deeplensFaceDetection:
    Properties:
      CodeUri: s3://deeplens-face-detection/a81b9438deaf80a5c500ca5307f46368
      Description: Outputs the JPEG bits to a FIFO file on AWS DeepLens
      Handler: greengrass_face_detection.function_handler
      MemorySize: 1536
      Role:
        Fn::Join:
        - ''
        - - 'arn:aws:iam::'
          - Ref: AWS::AccountId
          - :role/AWSDeepLensLambdaRole
      Runtime: python2.7
      Timeout: 3
    Type: AWS::Serverless::Function
  rekognizeEmotions:
    Properties:
      CodeUri: s3://deeplens-face-detection/a81b9438deaf80a5c500ca5307f46368
      Description: An Amazon S3 trigger that uses rekognition APIs to detect faces
      Events:
        BucketEvent1:
          Properties:
            Bucket:
              Ref: DeeplensHackBucket
            Events:
            - s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: faces/
                - Name: suffix
                  Value: jpg
          Type: S3
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role:
        Fn::Join:
        - ''
        - - 'arn:aws:iam::'
          - Ref: AWS::AccountId
          - :role/service-role/rekognize-faces-role
      Runtime: python2.7
      Tags:
        lambda-console:blueprint: rekognition-python
      Timeout: 3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
